name: Setup rust toolchain
description: Setup rust toolchain with the toolchain version input and sccache

inputs:
  toolchain:
    description: Toolchain name, such as 'stable', 'nightly', or '1.8.0'
    required: true
    default: stable
  target:
    description: Build target name, such as 'x86_64-unknown-linux-gnu', 'aarch64-apple-darwin', or 'x86_64-pc-windows-msvc'
    required: false

runs:
  using: composite
  steps:
    - name: Setup rust toolchain
      shell: bash
      run: |
        rustup toolchain install ${{ inputs.toolchain }} --profile default
        rustup default ${{ inputs.toolchain }}

    - name: Add build target
      if: "${{ inputs.target != '' }}"
      shell: bash
      run: rustup target add ${{ inputs.target }}

    - uses: mozilla-actions/sccache-action@v0.0.9

    - name: Setup rust cache variables
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "CARGO_INCREMENTAL=false" >> $GITHUB_ENV
