---
name: Super-Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Work around super-linter
        shell: bash
        run: |
          # Work-around for SHA detection
          # https://github.com/super-linter/super-linter/issues/6316#issuecomment-2510205626
          if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            echo 'GITHUB_BEFORE_SHA=${{ github.event.pull_request.base.sha }}' >> "${GITHUB_ENV}"
          fi
      - name: Run Super Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          # ASCII Possum is cute, but not necessary
          SUPPRESS_POSSUM: true
          # Only check new or modified files
          VALIDATE_ALL_CODEBASE: false
          # Language-specific linters
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          # Misc configuration
          ENFORCE_COMMITLINT_CONFIGURATION_CHECK: true
          VALIDATE_GIT_COMMITLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          # Do not rely on the statuses permission
          MULTI_STATUS: false
